
import { Inter } from 'next/font/google'
import '../globals.css'
import Sidebar from '../ui/dashboard/Sidebar/Sidebar'
import Navbar from '../ui/dashboard/Navbar/Navbar'
import { ContextProvider, useStateContext } from '../context/ContextProvider'
import { Provider } from 'react-redux'
import StoreProvider from '../redux/provider'
import { ThemeProvider } from '../context/ThemeProvider'
import { useSelector } from 'react-redux';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
    <html lang="en">
      <body className={`${inter.className} flex relative`} >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
          <ContextProvider>
              <div className='fixed z-20 top-0 left-0'>
                  <Sidebar/>
              </div>
              <div className={'w-full bg-gray-100 dark:bg-black min-h-screen lg:ml-20  overflow-x-hidden lg:px-10'}>
              <div className='mx-4 '>
                <div className='fixed z-10 w-full top-0 left-0 right-0 lg:pl-20 '>
                <Navbar />
                </div>
                {children}
              </div>
              </div> 
          </ContextProvider>
        </ThemeProvider>
        </body>
    </html>
    </StoreProvider>
  
  )
}
